name: Deploy HTML to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    permissions:  # Explicitly set permissions
      contents: read  # Read repository contents
      pages: write    # Permission to deploy to GitHub Pages
      id-token: write  # Enable OIDC for authentication

    environment:
      name: github-pages  # Define the environment for deployment

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Fetch the repository code

      - name: Set up GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload HTML to GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./  # Upload everything in the root directory

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
